on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - run: |
        repo=ghcr.io/charlieegan3/racket-gregor
        tag=$repo:$GITHUB_SHA
        latest=$repo:latest
        docker build -t $tag -t $latest .
        docker push $tag
        docker push $latest
